[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 26

[functions."count-scheduled"]
  schedule = "0 8 * * *"
